export const CONTRACT_ADDRESSES = {
  STAKING_CONTRACT: import.meta.env.VITE_STAKING_CONTRACT,
  STAKING_TOKEN: import.meta.env.VITE_STAKING_TOKEN,
};

export const PRECISION = {
  TOKEN_DECIMALS: 18,
  PERCENTAGE: 100,
  APR_PRECISION: 10000, 
};

export const TIME_CONSTANTS = {
  SECONDS_IN_MINUTE: 60,
  SECONDS_IN_HOUR: 3600,
  SECONDS_IN_DAY: 86400,
  SECONDS_IN_YEAR: 31536000,
};

export const UI_CONFIG = {
  REFRESH_INTERVAL: 30000,
  TRANSACTION_TIMEOUT: 300000, 
};
